version: "3.8"

services:
  fastapi:
    build: ./fastapi_app
    container_name: fastapi-ollama-client
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    restart: unless-stopped