FROM python:3.9.7

WORKDIR /code

# パッケージのインストール
RUN apt update && apt install -y ffmpeg 
RUN pip install --upgrade pip

# PyTorch + CUDA インストール
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# PyAnnote 設置
RUN pip install pyannote.audio==3.1 ffmpeg-python dotenv

# FastAPI & Uvicorn (REST API 서버용)
RUN pip install fastapi[all]==0.95.1 uvicorn[standard]==0.21.1 gunicorn==20.1.0 python-multipart

COPY ./app /code/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
